language: node_js

node_js:
  - "0.12"
  - "0.10"
  - "iojs-v2.0.0"

services:
  - mongodb

script: "npm run test-travis"
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
